---
# tasks file for podman
- name: Install podman
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - podman
    - podman-compose
  become: true
  become_method: ansible.builtin.sudo
